/* Main.ino file generated by New Project wizard
 *
 * Created:   Sat May 18 2019
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 *A simple program to demonstrate the multi tasking on arduino
 * Aim : 1) Genarate a square wave and
 *      2)Control a LED using a momentary switch indidually. 
 */

// Peripheral Configuration Code (do not edit)

int led1=7;   //D1 LED for square wave output
int led2=10;  //D2 LED for momentory switch 
int pushbtn=13;   //Push button to control D2 LED
int oncyc=0; //variable used to check the time period
int state=1; //variable used to check the state of the D1 LED

void ledAuto(); //function to create square wave
void ledPush(); //function to control D2 LED

void setup ()
{

//Pin i/p and o/p configuration

pinMode(led1,OUTPUT);
pinMode(led2,OUTPUT);
pinMode(pushbtn,INPUT);
}

void loop()
{
ledAuto();
ledPush();
}

void ledAuto()
{
if(oncyc==500)
{
digitalWrite(led1,HIGH);
state=0;
}
if(oncyc==0)
{
digitalWrite(led1,LOW);
state=1;
}

// delay function control

if(state==1)
{
  delay(1);
  oncyc++;
}
else
{ 
  delay(1);
  oncyc--;
}

}

//momentary switch control function

void ledPush()
{
if(digitalRead(pushbtn)==HIGH)
  digitalWrite(led2,HIGH);
if(digitalRead(pushbtn)==LOW)
  digitalWrite(led2,LOW);
}
